Atualizando gerador de runtime

diff --git a/makegtkruntime.sh.in b/makegtkruntime.sh.in
--- a/makegtkruntime.sh.in
+++ b/makegtkruntime.sh.in
@@ -9,30 +9,41 @@ TARGET_PATH=".bin/gtkruntime"
 rm -fr "$TARGET_PATH/*"
 mkdir -p "$TARGET_PATH"
 
+copyFile() {
+
+	GTKPATH=$(find "$GTK_PREFIX/bin" -name "$1")
+	SYSPATH=$(find "/bin" -name "$1")
+
+	if [ ! -z "$GTKPATH" ]; then
+		echo "$GTKPATH ..."
+		cp $GTKPATH "$TARGET_PATH"
+		if [ "$?" != "0" ]; then
+			echo "Can´t copy $GTKPATH"
+			return 1
+		fi
+	elif [ ! -z "$SYSPATH" ]; then
+		echo "$SYSPATH ..."
+		cp $SYSPATH "$TARGET_PATH"
+		if [ "$?" != "0" ]; then
+			echo "Can´t copy $SYSPATH"
+			return 1
+		fi
+
+	else
+		echo "Can´t find $1"
+		return 1
+	fi
+
+	return 0
+}
+
 copyFiles() {
 
 	while read FILE
 	do
-		GTKPATH=$(find "$GTK_PREFIX/bin" -name "$FILE")
-		SYSPATH=$(find "/bin" -name "$FILE")
-
-		if [ ! -z "$GTKPATH" ]; then
-			echo "$GTKPATH ..."
-			cp $GTKPATH "$TARGET_PATH"
-			if [ "$?" != "0" ]; then
-				echo "Can´t copy $GTKPATH"
-				exit -1
-			fi
-		elif [ ! -z "$SYSPATH" ]; then
-			echo "$SYSPATH ..."
-			cp $SYSPATH "$TARGET_PATH"
-			if [ "$?" != "0" ]; then
-				echo "Can´t copy $SYSPATH"
-				exit -1
-			fi
-
-		else
-			echo "Can´t find $FILE"
+		copyFile "$FILE"
+		if [ "$?" != "0" ]; then
+			exit -1
 		fi
 	done < $1
 	rm -f $1
@@ -78,7 +89,7 @@ libfreetype-6*.dll
 zlib1.dll
 libxml2-*.dll
 libpixman-1*.dll
-libpng15-*.dll
+libpng*.dll
 libgdk_pixbuf*.dll
 libgio-*.dll
 libjasper-*.dll
@@ -92,19 +103,21 @@ libpangowin32-1*.dll
 libatk-*.dll
 libcrypto-*.dll
 libssl-*.dll
-libgcc_s_sjlj-1.dll
-libgcc_s_seh-1.dll
 libharfbuzz-0.dll
-icule51.dll
-icuuc51.dll
-icudata51.dll
 libstdc++-6.dll
+icule53.dll
+icuuc53.dll
+icudata53.dll
 libgraphite2.dll
-gspawn-win32-helper-console.exe
-gspawn-win32-helper.exe
+gspawn-win*-helper-console.exe
+gspawn-win*-helper.exe
 gdk-pixbuf-query-loaders.exe
 EOF
 copyFiles $TEMPFILE
+
+# Copy optional files
+copyFile libgcc_s_sjlj-1.dll
+copyFile libgcc_s_seh-1.dll
 
 # Build locale dirs
 cat > $TEMPFILE << EOF
@@ -247,3 +260,6 @@ if [ "$GTK_VERSION" == "gtk+-3.0" ]; then
 else
 	gtk2
 fi
+
+echo $0 Complete
+
