Working on macos bundle.

diff --git a/mac/bundle b/mac/bundle
--- a/mac/bundle
+++ b/mac/bundle
@@ -38,13 +38,12 @@ mkdir -p ${APPDIR}/Contents/Resources/plugins
 
 install_libraries() {
 
-    # First copy the required libraries
+    # Copy the required libraries
     for path in $(otool -L ${1} | tail -n +2 | grep -v "/usr/lib/" | grep -v "/System" | cut -d\( -f1)
     do
         dpath="${APPDIR}/Contents/MacOS/lib/$(basename ${path})"
         
-        echo "Copying ${path} to ${dpath}"
-        cp "${path}" "${dpath}"
+        cp -v "${path}" "${dpath}"
         if [ "$?" != "0" ]; then
             echo "Error copying ${path}"
             exit -1
@@ -57,12 +56,26 @@ install_libraries() {
                 ${1}
     done
 
+    # Copy gdk pixbuf loaders
+    GDK_PIXBUF_SRC=$(pkg-config --variable=gdk_pixbuf_binarydir gdk-pixbuf-2.0)
+    GDK_PIXBUF_DIR=$(echo ${GDK_PIXBUF_SRC} | sed -e "s@$(pkg-config --variable=libdir gdk-pixbuf-2.0)@@g")
+
+    mkdir -p "${APPDIR}/Contents/MacOS/lib/${GDK_PIXBUF_DIR}/loaders"
+    for loader in $(find $(pkg-config --variable=gdk_pixbuf_binarydir gdk-pixbuf-2.0)/loaders -name "*.so")
+    do
+        cp -v "${loader}" "${APPDIR}/Contents/MacOS/lib/${GDK_PIXBUF_DIR}/loaders"
+        if [ "$?" != "0" ]; then
+            echo "Error copying ${loader}"
+            exit -1
+        fi
+    done
+
     # Resolve library dependencies
     again=1
     while [ "${again}" == "1" ]
     do
         again=0
-        for libname in $(find ${APPDIR}/Contents/MacOS/lib -name "*.dylib")
+        for libname in $(find ${APPDIR}/Contents/MacOS/lib -name "*.dylib") $(find ${APPDIR}/Contents/MacOS/lib -name "*.so")
         do
             echo "Checking ${libname}"
             for path in $(otool -L ${libname} | tail -n +2 | grep -v "@executable_path/" | grep -v "/System/" | grep -v "/usr/lib/" | cut -d\( -f1)
@@ -71,8 +84,7 @@ install_libraries() {
 
                 if [ ! -e "${dpath}" ]; then
                     again=1
-                    echo "Copying ${path} to ${dpath}"
-                    cp "${path}" "${dpath}"
+                    cp -v "${path}" "${dpath}"
                     if [ "$?" != "0" ]; then
                         echo "Error copying ${path}"
                         exit -1
@@ -88,6 +100,7 @@ install_libraries() {
             done
 
         done
+
     done
 
 }
