Debugging on macos.

diff --git a/mac/bundle b/mac/bundle
--- a/mac/bundle
+++ b/mac/bundle
@@ -33,9 +33,8 @@ mkdir -p ${APPDIR}
 mkdir -p ${APPDIR}/Contents
 mkdir -p ${APPDIR}/Contents/MacOS
 mkdir -p ${APPDIR}/Contents/MacOS/lib
-mkdir -p ${APPDIR}/Contents/MacOS/bin
 mkdir -p ${APPDIR}/Contents/Resources
-
+mkdir -p ${APPDIR}/Contents/Resources/plugins
 
 install_libraries() {
 
@@ -149,6 +148,19 @@ if [ "$?" != "0" ]; then
     echo "Error copying ${APPNAME}"
     exit -1
 fi
+
+cp .build/${APPNAME}.ui.xml ${APPDIR}/Contents/Resources
+if [ "$?" != "0" ]; then
+    echo "Error copying ${APPNAME}.ui.xml"
+    exit -1
+fi
+
+cp -v mac/info.plist ${APPDIR}/Contents
+if [ "$?" != "0" ]; then
+    echo "Error copying info.plist"
+    exit -1
+fi
+
 
 install_libraries ${APPDIR}/Contents/MacOS/${APPNAME}
 install_schemas
