Debugging macos actions & bundle.

diff --git a/mac/bundle b/mac/bundle
--- a/mac/bundle
+++ b/mac/bundle
@@ -43,6 +43,8 @@ install_libraries() {
     for path in $(otool -L ${1} | grep -v "/usr/lib/" | grep -v "^${1}" | grep -v "/System" | cut -d\( -f1)
     do
         dpath="${APPDIR}/Contents/MacOS/lib/$(basename ${path})"
+        
+        echo "Copying ${path} to ${dpath}"
         cp "${path}" "${dpath}"
         if [ "$?" != "0" ]; then
             echo "Error copying ${path}"
@@ -56,7 +58,38 @@ install_libraries() {
                 ${1}
     done
 
-    otool -L ${1}
+    # Resolve library dependencies
+    again=1
+    while [ "${again}" == "1" ]
+    do
+        again=0
+        for libname in $(find ${APPDIR}/Contents/MacOS/lib -name "*.dylib")
+        do
+            echo "Checking ${libname}"
+            for path in $(otool -L ${libname} | grep -v "${libname}" | grep -v "@executable_path/" | grep -v "/System/" | grep -v "/usr/lib/" | cut -d\( -f1)
+            do
+                dpath="${APPDIR}/Contents/MacOS/lib/$(basename ${path})"
+                if [ -e "${dpath}" ]; then
+                    continue
+                fi
+
+                again=1
+                echo "Copying ${path} to ${dpath}"
+                cp "${path}" "${dpath}"
+                if [ "$?" != "0" ]; then
+                    echo "Error copying ${path}"
+                    exit -1
+                fi
+
+                install_name_tool \
+                    -change \
+                        ${path} \
+                        @executable_path/lib/$(basename ${path}) \
+                        ${1}
+
+            done
+        done
+    done
 
 }
 
